name: Build Aurex CLI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Swift
      uses: apple/setup-swift@v1
      with:
        swift-version: '5.9.2'

    - name: Build with SwiftPM
      run: swift build -c release

    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: aurex-binary
        path: .build/release/aurex
